name: ghcli

on:
  workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 #descargar c贸digo
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/wpm-api/WisdomPetMedicine.sln
    - name: Build
      run: dotnet build src/wpm-api/WisdomPetMedicine.sln --no-restore
    - name: Test
      run: dotnet test src/wpm-api/WisdomPetMedicine.sln --no-build --verbosity normal
  docker:
     name: Contenerizaci贸n con Docker y .NET
     runs-on: ubuntu-latest
     needs: [build] #esta opci贸n es para decirle al job "docker" no se ejecute hasta que el job "build se haya ejecutado"
     steps:
     - uses: actions/checkout@v3 #descargar c贸digo
     - name: docker build
       run: docker build src/wpm-api --file src/wpm-api/WisdomPetMedicine.Api/Dockerfile --tag curso-github