name: Github Token

on:
   push:
     branches: [ "main" ]
   pull_request:
     branches: [ "main" ]
jobs:
    build:
  
      runs-on: ubuntu-latest
      env:
          SOLUTION_PATH: src/wpm-api/WisdomPetMedicine.sln
      steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore $SOLUTION_PATH
      - name: Build
        run: dotnet build $SOLUTION_PATH --no-restore
      - name: Test
        run: dotnet test $SOLUTION_PATH --no-build --verbosity normal
    docker:
       name: Contenerización con Docker y .NET
       runs-on: ubuntu-latest
       env:
          DOCKERFILE_PATH: src/wpm-api/WisdomPetMedicine.Api/Dockerfile
       needs: [build] #esta opción es para decirle al job "docker" no se ejecute hasta que el job "build se haya ejecutado"
       steps:
       - uses: actions/checkout@v3 #descargar código
       - name: docker build
         run: docker build src/wpm-api --file $DOCKERFILE_PATH --tag hannz151/curso-github:${{github.run_number}}
       - uses: docker/login-action@v2
         name: Login en Docker Hub
         with:
            username: USUARIOINCORRECTO
            password: PASSWORDINCORRECTO
       - name: Crear un issue con el API REST
         if: ${{failure()}}
         run: |
           curl --request POST \
           --url https://api.github.com/repos/${{ github.repository }}/issues \
           --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
           --header 'content-type: application/json' \
           --data '{
           "title": "No se puede autenticar con Docker Hub",
           "body": "Error en el workflow **${{ github.workflow }}**."
           }' \
           --fail
