name: ghcli

on:
  workflow_dispatch:
    inputs:
        tag:
            description: Etiqueta para la imagen de docker
            required: true
            default: latest

jobs:
  show:
    runs-on: ubuntu-latest
    steps:
        - name: Mostrar valores de variables de ambiente
          run: echo $GITHUB_ACTION && 
                echo $GITHUB_EVENT_NAME && 
                echo $GITHUB_REPOSITORY && 
                echo $GITHUB_RUN_NUMBER &&
                echo $GITHUB_WORKFLOW &&
                echo $GITHUB_WORKSPACE &&
                echo $RUNNER_NAME &&
                echo $RUNNER_OS &&
                echo $RUNNER_ARCH